version: "3.8"

services:
  php-atcoder:
    # カレントディレクトリでイメージを構築
    build: .
    # カレントディレクトリをコンテナへマウント
    volumes:
      - ../php.ini:/usr/local/etc/php/php.ini
      - ../html:/var/www/html
    # プロセスを継続させてコンテナの正常終了を防ぐ
    stdin_open: true
    ports:
      - "8080:80"
